services:
  app:
    image: piandarduinoguy/security-camera-micro-service
    devices:
      - /dev/vchiq:/dev/vchiq # expose camera device to the docker container
    volumes:
      - /opt/vc:/opt/vc # make dependencies needed by PiCamera available to it, located at /opt/vc on the RaspberryPi
      - /usr/lib:/usr/lib
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib # having access to the PiCamera dependencies, instruct OS to look in the lib directory
      RABBITMQ_HOST_IP:
      SECURITY_CONFIG_EXCHANGE_NAME: fanout_exchange
      SECURITY_CONFIG_QUEUE_NAME: updated.security.config
      LOGGING_FILE_DIRECTORY: /logs
      PIR_SENSOR_PIN: 4
      PIR_NUM_READINGS: 10
      PIR_DETECTIONS_PER_SECOND: 5
      PIR_THRESHOLD: 0.2
      LED_PIN: 26
      SECURITY_MICRO_SERVICE_HOST_IP: 192.168.3.153
      SECURITY_MICRO_SERVICE_HOST_PORT: 8082
      SECURITY_MICRO_SERVICE_CONTEXT_PATH: /security
      SECURITY_CAMERA_MICROSERVICE_CAPTURE_DIRECTORY: /captures

    privileged: true